# Generated by Django 6.0.2 on 2026-02-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_view_hestia', '0002_alter_tipohabitacion_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposala',
            name='descripcion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
