# Generated by Django 6.0.2 on 2026-03-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_view_hestia', '0002_alter_tipohabitacion_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
