# Generated by Django 6.0.2 on 2026-02-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_view_hestia', '0003_alter_tiposala_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipohabitacion',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tiposala',
            name='descripcion',
            field=models.CharField(blank=True, default='-', max_length=250),
            preserve_default=False,
        ),
    ]
