# Generated by Django 6.0.2 on 2026-03-02 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_view_hestia', '0002_alter_tipohabitacion_descripcion_and_more'),
        ('api_view_hestia', '0004_alter_tipohabitacion_descripcion_and_more'),
    ]

    operations = [
    ]
