# Generated by Django 6.0.2 on 2026-03-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_view_hestia', '0005_merge_20260302_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposala',
            name='descripcion',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
